AWSTemplateFormatVersion: '2010-09-09'

Parameters:
  RepositoryName:
    Type: String
    Default: todo

Resources:
  ECR:
    Type: AWS::ECR::Repository
    Properties:
      EncryptionConfiguration:
        EncryptionType: KMS
      ImageTagMutability: MUTABLE
      LifecyclePolicy:
        LifecyclePolicyText: |
          {
            "rules": [
              {
                "rulePriority": 1,
                "description": "Expire untagged images older than 7 days",
                "selection": {
                  "tagStatus": "untagged",
                  "countType": "sinceImagePushed",
                  "countUnit": "days",
                  "countNumber": 7
                },
                "action": { "type": "expire" }
              },
              {
                "rulePriority": 2,
                "description": "Keep last 10 images",
                "selection": {
                  "tagStatus": "any",
                  "countType": "imageCountMoreThan",
                  "countNumber": 10
                },
                "action": { "type": "expire" }
              }
            ]
          }
      RepositoryName: !Ref RepositoryName
      Tags:
        - Key: Name
          Value: !Ref RepositoryName

Outputs:
  RepositoryName:
    Value: !Ref RepositoryName
    Description: ECR repository name

  RepositoryUri:
    Value: !Sub '${AWS::AccountId}.dkr.ecr.${AWS::Region}.amazonaws.com/${RepositoryName}'
    Description: ECR repository URI

  RepositoryArn:
    Value: !GetAtt ECR.Arn
    Description: ECR repository ARN
